name: Build ZMK firmware

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your config
        uses: actions/checkout@v4
        with:
          path: config

      - name: Build LEFT
        uses: zmkfirmware/zmk-build@v1
        with:
          board: nice_nano_v2
          shield: my_split_left
          config-path: config
          archive-name: my_split_left-nice_nano_v2

      - name: Build RIGHT
        uses: zmkfirmware/zmk-build@v1
        with:
          board: nice_nano_v2
          shield: my_split_right
          config-path: config
          archive-name: my_split_right-nice_nano_v2

